### PR TITLE
Use Queue.writeTexture for textured cube

### PR DESCRIPTION
**Pull request by kvark**
See https://gpuweb.github.io/gpuweb/#dom-gpuqueue-writetexture

### CODE REVIEW

**Comment by tsherif** [comment]
Nice, thanks!

**Comment by tsherif** [comment]
@kvark This doesn't seem to be working for me in Chrome Canary 86.0.4204.0. Is this working for you somewhere?

**Comment by kvark** [comment]
@tsherif I'm working on Firefox changes that run this fine. And I can confirm this is good from the API usage perspective.
Surprised it doesn't work in Canary though, since `writeBuffer` is used, and they were introduced roughly at the same time.
Perhaps, we should back out the change from here and re-land it in a week or two when Chrome and Firefox are updated?

**Comment by tsherif** [comment]
No worries. I kept your change but just put it behind a check that `Queue.writeTexture` exists: https://github.com/tsherif/webgpu-examples/commit/34b27e68f0b4187cf233ccceddb37d84908378ba

I can remove the fallback once it's generally available.

**Pull request merged**
